import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import API from "../services/api";

function ExportPDF() {

    const downloadPDF = async () => {

        try {

            const res = await API.get("/expenses");
            const expenses = res.data;
           
const totalExpense = expenses.reduce(
    (sum, item) => sum + Number(item.amount),
    0
);

const averageExpense =
    expenses.length > 0
        ? (totalExpense / expenses.length).toFixed(2)
        : 0;

const biggestExpense = expenses.reduce(
    (max, item) =>
        Number(item.amount) > Number(max.amount) ? item : max,
    expenses[0]
);

const today = new Date().toLocaleDateString();

            const doc = new jsPDF();

            doc.setFillColor(33, 150, 243);
doc.rect(0, 0, 220, 35, "F");

doc.setTextColor(255, 255, 255);
doc.setFontSize(24);
doc.text("ExpenseIQ", 14, 18);

doc.setFontSize(13);
doc.text("AI Financial Report", 14, 28);

doc.setTextColor(0, 0, 0);

doc.setFontSize(11);
doc.text(`Generated on: ${today}`, 14, 45);

doc.setFontSize(16);
doc.text("Summary", 14, 60);

doc.setFontSize(12);
doc.text(`Total Expenses : ₹${totalExpense}`, 20, 72);

doc.text(`Transactions : ${expenses.length}`, 20, 82);

doc.text(`Average Expense : ₹${averageExpense}`, 20, 92);

doc.text(
    `Biggest Expense : ${biggestExpense.title} (₹${biggestExpense.amount})`,
    20,
    102
);

            autoTable(doc, {
                startY: 115,
                head: [["Title", "Category", "Amount", "Payment", "Date"]],
                body: expenses.map((expense) => [
                    expense.title,
                    expense.category,
                    `₹${expense.amount}`,
                    expense.paymentMethod,
                    new Date(expense.date).toLocaleDateString(),
                ]),
            });
            doc.setFontSize(10);

doc.text(
    "Generated by ExpenseIQ AI Assistant",
    14,
    doc.lastAutoTable.finalY + 15
);

doc.text(
    "This report is automatically generated.",
    14,
    doc.lastAutoTable.finalY + 22
);

            doc.save("ExpenseIQ_Report.pdf");

        } catch (error) {

            console.log(error);

        }

    };

    return (

        <button
            className="btn btn-danger mb-3"
            onClick={downloadPDF}
        >
            📄 Download Expense Report
        </button>

    );

}

export default ExportPDF;